#!/bin/bash 
# Fetch the source from the upstream repo and download it on the user machine 
set -euo pipefail IFS=$'\n\t' 
# Change to temporary directory 
cd $(mktemp -d) 

# Add brave browser source
echo 'Installing build dependencies...'
echo 'Adding trusted signed key...'
echo 'Fetching upstream source...'

sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg 

echo 'Adding upstream source to local sources...' 
echo 'deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list' 

echo 'Run the command sudo apt install brave-browser to install Brave Browser'
echo '-----------------------------'

# Add Google Chrome source
echo 'Installing build dependencies...' 
echo 'Adding trusted signed key...' 
echo 'Fetching upstream source...' 

sudo curl -fsSLo /etc/apt/trusted.gpg.d/google-chrome-keyring.asc https://dl-ssl.google.com/linux/linux_signing_key.pub 
sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome-browser.list' 

echo 'Run the command sudo apt install google-chrome-stable to install Google Chrome' 
echo '-----------------------------'

# Add Albert launcher source
echo 'Installing build dependencies...' 
echo 'Adding upstream source to local sources...' 

echo 'deb http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_22.04/ /' | sudo tee /etc/apt/sources.list.d/home:manuelschneid3r.list 

echo 'Adding upstream gpg key to local keyring for trust...' 
curl -fsSL https://download.opensuse.org/repositories/home:manuelschneid3r/xUbuntu_22.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_manuelschneid3r.gpg > /dev/null 

echo 'Updating sources...' 
echo 'Run the command sudo apt install albert to install the Albert application launcher'
echo '-----------------------------'

# Update entries
sudo apt update
